### ISSUE TITLE
Cannot create a patch from a json node

### ISSUE THREAD

**Issue by xelamitchell** [fge/json-patch#25]
After successfully getting a JsonNode from a replace json representation, attempting to use JsonPatch.fromJson(JsonNode) explodes the following exception:

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of FIELD_NAME token

The Json replace (as JsonNode): {"op":"replace","path":"/name","value":"Test"}

The code:

        final ObjectMapper mapper = new ObjectMapper();
        final JsonNode node = mapper.valueToTree(request);
        logger.debug("{}", node);
        JsonPatch patch = JsonPatch.fromJson(node);

**Comment by fge** [comment]
This is normal, since this is not a valid JSON Patch!

A JSON Patch is an _array_ of JSON Patch operations. And what is more, your operation is not even valid here.

Maybe you mean to create a JSON _Merge_ Patch instead?

**Comment by xelamitchell** [comment]
Hi fge,
Thanks for that. Changing the json string to [{"op":"replace","path":"/name","value":"Test"}] worked with a JsonMergePatch based on an ArrayNode. Not quite sure about the difference between the JsonPatch and JsonMergePatch though.

Many thanks

**Comment by fge** [comment]
Ooh, waitaminute.

The difference is FUNDAMENTAL!

As the README says:

* JSON Patch is [RFC 6902](http://tools.ietf.org/html/rfc6902);
* JSON Merge Patch is [RFC 7386](http://tools.ietf.org/html/rfc7386).

The two are fundamentally different!

Admittedly, the documentation is a little on the lacking side as to the differences, but in short, a JSON Patch is an array of patch operations, and a JSON Merge Patch is another way to patch a JSON value which handles JSON Objects in a particular way.

**Comment by xelamitchell** [comment]
Many thanks man!

**Comment by crazyproger** [comment]
Am I right that this library can not prepare valid JSON Merge Patch from two JSON document version?
Didn't found code to produce it, in opposite to JSON Patch.
