### ISSUE TITLE
 Can not deserialize instance of java.util.ArrayList out of FIELD_NAME token

### ISSUE THREAD

**Issue by slvs** [fge/json-patch#29]
I'm using json-patch-1.9, and the following simple code doesn't work:

	    	String origJson = "{\"id\":1}";
	    	String newJson =  "{\"id\":1}";
	    	ObjectMapper mapper = new ObjectMapper();
	    	JsonNode origNode = mapper.readTree(origJson);
	    	JsonNode newNode = mapper.readTree(newJson);
	    	JsonPatch patchNew = JsonPatch.fromJson(newNode);
	    	JsonNode diffs = patchNew.apply(origNode);

The call to JsonPatch.fromJson(newNode) throws the following exception:

com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of FIELD_NAME token

Any idea what is wrong?

**Comment by jhuffaker** [comment]
I assume the JsonPatch expects json that looks like [{"op": "add", "path": "/id", "value": 1}].

Described at:
https://tools.ietf.org/html/rfc6902

**Comment by fge** [comment]
Exactly what @jhuffaker said; here you are trying to use a JSON Merge Patch, not a JSON Patch.
